/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

(* top =  1  *)
(* src = "stupid.v:1.1-27.10" *)
module stupid(clk, inst, in_mem, we, out_mem, out_adr, out_pc);
  (* src = "stupid.v:2.23-2.26" *)
  input clk;
  wire clk;
  (* src = "stupid.v:3.23-3.27" *)
  input [7:0] inst;
  wire [7:0] inst;
  (* src = "stupid.v:4.23-4.29" *)
  input [7:0] in_mem;
  wire [7:0] in_mem;
  (* src = "stupid.v:6.23-6.25" *)
  output we;
  wire we;
  (* src = "stupid.v:7.23-7.30" *)
  output [7:0] out_mem;
  wire [7:0] out_mem;
  (* src = "stupid.v:8.23-8.30" *)
  output [5:0] out_adr;
  wire [5:0] out_adr;
  (* src = "stupid.v:9.23-9.29" *)
  output [5:0] out_pc;
  reg [5:0] out_pc = 6'h00;
  (* src = "stupid.v:16.5-26.8" *)
  wire [7:0] _000_;
  (* src = "stupid.v:16.5-26.8" *)
  wire [5:0] _001_;
  (* force_downto = 32'd1 *)
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [7:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [7:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _004_;
  (* force_downto = 32'd1 *)
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _005_;
  (* force_downto = 32'd1 *)
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [7:0] _006_;
  (* force_downto = 32'd1 *)
  (* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [5:0] _007_;
  (* force_downto = 32'd1 *)
  (* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [5:0] _008_;
  (* force_downto = 32'd1 *)
  (* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [5:0] _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire [3:0] _021_;
  wire [1:0] _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire [5:0] _030_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _031_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _032_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _033_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _034_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _035_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _036_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _037_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _038_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _039_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _040_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _041_;
  (* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _042_;
  (* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _043_;
  (* src = "stupid.v:11.15-11.16" *)
  reg [7:0] a = 8'h00;
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    a[0] <= _018_;
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    a[1] <= _017_;
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    a[2] <= _016_;
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    a[3] <= _015_;
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    a[4] <= _014_;
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    a[5] <= _013_;
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    a[6] <= _012_;
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    a[7] <= _019_;
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    out_pc[0] <= _001_[0];
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    out_pc[1] <= _001_[1];
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    out_pc[2] <= _001_[2];
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    out_pc[3] <= _001_[3];
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    out_pc[4] <= _001_[4];
  (* src = "stupid.v:16.5-26.8" *)
  always @(posedge clk)
    out_pc[5] <= _001_[5];
  assign _012_ = _020_ ? _000_[6] : a[6];
  assign _013_ = _020_ ? _000_[5] : a[5];
  assign _014_ = _020_ ? _000_[4] : a[4];
  assign _015_ = _020_ ? _000_[3] : a[3];
  assign _016_ = _020_ ? _000_[2] : a[2];
  assign _017_ = _020_ ? _000_[1] : a[1];
  assign _018_ = _020_ ? _000_[0] : a[0];
  assign _019_ = _020_ ? _000_[7] : a[7];
  assign _005_[0] = ~_004_[0];
  assign _010_ = ~inst[7];
  assign _011_ = ~inst[6];
  assign _009_[1] = out_pc[1] ^(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  out_pc[0];
  assign _009_[2] = out_pc[2] ^(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _007_[1];
  assign _009_[3] = out_pc[3] ^(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _007_[2];
  assign _009_[4] = out_pc[4] ^(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _007_[3];
  assign _009_[5] = out_pc[5] ^(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _007_[4];
  assign _005_[1] = _004_[1] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _003_[0];
  assign _005_[2] = _004_[2] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _003_[1];
  assign _005_[3] = _004_[3] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _003_[2];
  assign _005_[4] = _004_[4] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _003_[3];
  assign _005_[5] = _004_[5] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _003_[4];
  assign _005_[6] = _004_[6] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _003_[5];
  assign _005_[7] = _004_[7] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _003_[6];
  assign _007_[2] = out_pc[2] &(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _007_[1];
  assign _007_[4] = out_pc[4] &(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _007_[3];
  assign _007_[3] = _043_ &(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _007_[1];
  assign _043_ = out_pc[3] &(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  out_pc[2];
  assign _007_[1] = out_pc[1] &(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  out_pc[0];
  assign _006_[0] = a[0] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _002_[0];
  assign _006_[1] = a[1] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _002_[1];
  assign _006_[2] = a[2] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _002_[2];
  assign _006_[3] = a[3] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _002_[3];
  assign _006_[4] = a[4] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _002_[4];
  assign _006_[5] = a[5] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _002_[5];
  assign _006_[6] = a[6] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _002_[6];
  assign _004_[0] = a[0] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _002_[0];
  assign _004_[1] = a[1] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _002_[1];
  assign _004_[2] = a[2] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _002_[2];
  assign _004_[3] = a[3] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _002_[3];
  assign _004_[4] = a[4] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _002_[4];
  assign _004_[5] = a[5] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _002_[5];
  assign _004_[6] = a[6] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _002_[6];
  assign _004_[7] = a[7] ^(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _002_[7];
  assign _003_[2] = _006_[2] |(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _038_;
  assign _038_ = _004_[2] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _003_[1];
  assign _039_ = _004_[4] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _003_[3];
  assign _003_[5] = _042_ |(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _037_;
  assign _037_ = _036_ &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _003_[3];
  assign _040_ = _004_[6] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _003_[5];
  assign _003_[6] = _006_[6] |(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _040_;
  assign _003_[3] = _041_ |(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _034_;
  assign _034_ = _035_ &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _003_[1];
  assign _036_ = _004_[5] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _004_[4];
  assign _042_ = _006_[5] |(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _033_;
  assign _033_ = _004_[5] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _006_[4];
  assign _035_ = _004_[3] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _004_[2];
  assign _041_ = _006_[3] |(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _032_;
  assign _032_ = _004_[3] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _006_[2];
  assign _003_[4] = _006_[4] |(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _039_;
  assign _003_[1] = _006_[1] |(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _031_;
  assign _031_ = _004_[1] &(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _003_[0];
  assign _003_[0] = _006_[0] |(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:231.10-231.28" *)  _004_[0];
  assign _020_ = _028_ | _029_;
  assign _025_ = _011_ |(* src = "stupid.v:14.17-14.31" *)  inst[7];
  assign _026_ = _011_ |(* src = "stupid.v:22.33-22.33|stupid.v:18.9-25.16" *)  _010_;
  assign _027_ = inst[6] |(* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *)  _010_;
  assign _021_[0] = a[0] |(* src = "stupid.v:24.21-24.27" *)  a[1];
  assign _021_[1] = a[2] |(* src = "stupid.v:24.21-24.27" *)  a[3];
  assign _021_[2] = a[4] |(* src = "stupid.v:24.21-24.27" *)  a[5];
  assign _021_[3] = a[6] |(* src = "stupid.v:24.21-24.27" *)  a[7];
  assign _022_[0] = _021_[0] |(* src = "stupid.v:24.21-24.27" *)  _021_[1];
  assign _022_[1] = _021_[2] |(* src = "stupid.v:24.21-24.27" *)  _021_[3];
  assign _023_ = _022_[0] |(* src = "stupid.v:24.21-24.27" *)  _022_[1];
  assign _024_ = inst[6] |(* src = "stupid.v:18.25-18.25|stupid.v:18.9-25.16" *)  inst[7];
  assign we = ~(* src = "stupid.v:14.17-14.31" *) _025_;
  assign _028_ = ~(* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *) _027_;
  assign _029_ = ~(* src = "stupid.v:18.25-18.25|stupid.v:18.9-25.16" *) _024_;
  assign _030_[0] = _023_ ? (* src = "stupid.v:24.21-24.27|stupid.v:24.17-24.49" *) _008_[0] : inst[0];
  assign _030_[1] = _023_ ? (* src = "stupid.v:24.21-24.27|stupid.v:24.17-24.49" *) _009_[1] : inst[1];
  assign _030_[2] = _023_ ? (* src = "stupid.v:24.21-24.27|stupid.v:24.17-24.49" *) _009_[2] : inst[2];
  assign _030_[3] = _023_ ? (* src = "stupid.v:24.21-24.27|stupid.v:24.17-24.49" *) _009_[3] : inst[3];
  assign _030_[4] = _023_ ? (* src = "stupid.v:24.21-24.27|stupid.v:24.17-24.49" *) _009_[4] : inst[4];
  assign _030_[5] = _023_ ? (* src = "stupid.v:24.21-24.27|stupid.v:24.17-24.49" *) _009_[5] : inst[5];
  assign _001_[0] = _026_ ? (* src = "stupid.v:22.33-22.33|stupid.v:18.9-25.16" *) _008_[0] : _030_[0];
  assign _001_[1] = _026_ ? (* src = "stupid.v:22.33-22.33|stupid.v:18.9-25.16" *) _009_[1] : _030_[1];
  assign _001_[2] = _026_ ? (* src = "stupid.v:22.33-22.33|stupid.v:18.9-25.16" *) _009_[2] : _030_[2];
  assign _001_[3] = _026_ ? (* src = "stupid.v:22.33-22.33|stupid.v:18.9-25.16" *) _009_[3] : _030_[3];
  assign _001_[4] = _026_ ? (* src = "stupid.v:22.33-22.33|stupid.v:18.9-25.16" *) _009_[4] : _030_[4];
  assign _001_[5] = _026_ ? (* src = "stupid.v:22.33-22.33|stupid.v:18.9-25.16" *) _009_[5] : _030_[5];
  assign _000_[0] = _027_ ? (* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *) in_mem[0] : _005_[0];
  assign _000_[1] = _027_ ? (* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *) in_mem[1] : _005_[1];
  assign _000_[2] = _027_ ? (* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *) in_mem[2] : _005_[2];
  assign _000_[3] = _027_ ? (* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *) in_mem[3] : _005_[3];
  assign _000_[4] = _027_ ? (* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *) in_mem[4] : _005_[4];
  assign _000_[5] = _027_ ? (* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *) in_mem[5] : _005_[5];
  assign _000_[6] = _027_ ? (* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *) in_mem[6] : _005_[6];
  assign _000_[7] = _027_ ? (* src = "stupid.v:20.29-20.29|stupid.v:18.9-25.16" *) in_mem[7] : _005_[7];
  assign _008_[0] = ~(* src = "stupid.v:17.19-17.29|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) out_pc[0];
  assign _002_[0] = ~(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) in_mem[0];
  assign _002_[1] = ~(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) in_mem[1];
  assign _002_[2] = ~(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) in_mem[2];
  assign _002_[3] = ~(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) in_mem[3];
  assign _002_[4] = ~(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) in_mem[4];
  assign _002_[5] = ~(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) in_mem[5];
  assign _002_[6] = ~(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) in_mem[6];
  assign _002_[7] = ~(* src = "stupid.v:22.22-22.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) in_mem[7];
  assign _009_[0] = _008_[0];
  assign _007_[0] = out_pc[0];
  assign _008_[5:1] = out_pc[5:1];
  assign out_adr = inst[5:0];
  assign out_mem = a;
endmodule
