import type { LabId } from './circuits'
export type Question = {prompt:string,choices:string[],answer:number,why:string,hint:string}
export type Lesson = {slug:string,title:string,deck:string,minutes:number,phase:string,goals:string[],labs:(LabId|'transistors'|'programming')[],questions:Question[],sources:{title:string,url:string}[]}
const source=(title:string,url:string)=>({title,url})
const cmos=source('computation structures · cmos','https://computationstructures.org/notes/cmos/notes.html')
const seq=source('computation structures · sequential logic','https://computationstructures.org/notes/sequential_logic/notes.html')
const arithmetic=source('computation structures · design tradeoffs','https://computationstructures.org/notes/tradeoffs/notes.html')
const q=(prompt:string,choices:string[],answer:number,why:string,hint:string):Question=>({prompt,choices,answer,why,hint})
export const lessons:Lesson[]=[
 {slug:'transistors',title:'a switch made of silicon',deck:'electric fields, complementary switches, and the first real logic gate.',minutes:25,phase:'01 / electricity → logic',goals:['distinguish voltage from current','follow a pull-up and pull-down path','explain why the transistor pair inverts'],labs:['transistors'],sources:[cmos],questions:[
 q('in our cmos inverter, the input is low. what fixes the output high?',['the n-channel transistor','the p-channel path to the positive supply','the lack of current automatically means 1'],1,'the p-channel switch connects the output to the positive supply while the n-channel path is open. a disconnected output would float, not become 1.','trace a conducting path from the output to a supply rail.'),
 q('a cmos nand gate has both inputs high. what happens?',['the series n-channel path conducts, giving 0','both p-channel switches conduct, giving 1','the output must float'],0,'both n-channel switches conduct in series, while both p-channel pull-up switches are off.','nand is not-and: it is low only for 11.') ]},
 {slug:'gates',title:'one gate is enough',deck:'build not, and, and or using nothing but nand gates.',minutes:25,phase:'01 / electricity → logic',goals:['read a truth table','wire outputs to inputs without shorting drivers','construct three functions from nand'],labs:['nand-not','nand-and','nand-or'],sources:[cmos],questions:[
 q('what is NAND(a, a)?',['always 0','NOT a','a'],1,'a AND a equals a. the nand output complements it.','try a=0 and a=1 separately.'),
 q('how do you make OR from three nand gates?',['nand the inputs, then invert twice','invert each input with a nand, then nand those results','connect two outputs to the same wire'],1,'NOT((NOT a) AND (NOT b)) is a OR b. connecting independent outputs is a short, not a logic operation.','use the truth table, or de morgan’s law.') ]},
 {slug:'bits',title:'numbers are a convention',deck:'eight independent wires become a byte only because we agree how to read them.',minutes:20,phase:'01 / electricity → logic',goals:['convert a bit pattern to a number','distinguish a value from its address','interpret the same bits as signed or unsigned'],labs:['byte'],sources:[],questions:[
 q('what unsigned value does 00101010 represent?',['21','42','84'],1,'32 + 8 + 2 = 42. bit zero, at the right of the written number, has weight 1.','add the powers of two for the set bits.'),
 q('how should an eight-bit two’s-complement 11111111 be read?',['255 only','−1; unsigned interpretation would be 255','the circuit cannot represent it'],1,'the physical bits do not change. signed interpretation gives the top bit weight −128 rather than +128.','−128 + 64 + 32 + 16 + 8 + 4 + 2 + 1.') ]},
 {slug:'selection',title:'choosing a path',deck:'multiplexers, shared signals, and crossing wires without connecting them.',minutes:25,phase:'02 / logic → datapath',goals:['build a two-input mux','identify data versus control','use an actual crossover with independent channels'],labs:['mux','cross'],sources:[],questions:[
 q('a mux has a=1, b=0, s=1. its output is…',['1','0','a stored bit'],1,'our mux selects b when s=1 and a when s=0. it stores nothing.','the select bit chooses which input reaches the output.'),
 q('what should happen when one crossover input changes?',['both outputs change','only that channel’s paired output follows','the device performs XOR'],1,'Cross is a routing component: TL → BR and TR → BL are independent.','a crossover prevents an electrical junction.') ]},
 {slug:'addition',title:'teach wires to add',deck:'derive the half adder, add a carry input, then repeat the slice.',minutes:35,phase:'02 / logic → datapath',goals:['derive sum and carry','chain full adders from low bit to high bit','separate arithmetic carry from signed overflow'],labs:['half','full','adder4'],sources:[arithmetic],questions:[
 q('a full adder sees a=1, b=1, cin=1. what are sum and cout?',['sum=1, cout=1','sum=0, cout=1','sum=1, cout=0'],0,'1+1+1=3, whose two-bit representation is 11.','the sum output is the low bit.'),
 q('four-bit 0111 + 0001 produces 1000. which statement is correct?',['carry-out must be 1','unsigned 8 is correct, but signed +8 is outside the four-bit range','the adder is broken'],1,'unsigned 7+1 fits in four bits. in signed four-bit arithmetic the range is −8 through +7, so this is signed overflow without carry-out.','carry and signed overflow answer different questions.') ]},
 {slug:'subtraction',title:'subtraction without a new machine',deck:'use the adder again, with inverted bits and a carry-in of one.',minutes:25,phase:'02 / logic → datapath',goals:['derive a − b as a + ~b + 1','understand modulo arithmetic','read carry-out as no-borrow'],labs:['sub4','accumulator'],sources:[arithmetic],questions:[
 q('our SUB x instruction eventually means…',['memory[x] − accumulator','accumulator − memory[x], stored back in accumulator','x − accumulator'],1,'x is an address, not the value subtracted. the accumulator is the implicit left operand.','load x, subtract y, store z computes memory[z] = memory[x] − memory[y].'),
 q('four-bit 0 − 1 leaves which result bits?',['0000','1111','1000'],1,'the result wraps modulo 16 to 15, also the two’s-complement encoding of −1.','ignore the carry beyond the four stored result bits.') ]},
 {slug:'state',title:'remembering yesterday',deck:'feedback creates storage; a clock tells that storage when to change.',minutes:35,phase:'03 / datapath → state',goals:['set and reset a latch','distinguish a latch from an edge-triggered dff','build a register with a load enable'],labs:['latch','dff','register'],sources:[seq],questions:[
 q('after a rising edge captures 1, D becomes 0 while CLK remains high. a DFF’s Q…',['immediately becomes 0','remains 1 until another rising edge','oscillates'],1,'a positive-edge DFF samples at the low-to-high transition, not continuously while the clock is high.','being high is a level; becoming high is an edge.'),
 q('how does a register hold its old value without a special enable flip-flop?',['disconnect its clock arbitrarily','feed Q back to D through a selecting mux','force D to zero'],1,'the input mux chooses either new data or old Q. sampling Q again keeps the state unchanged.','a DFF plus a feedback mux implements load/hold.') ]},
 {slug:'memory',title:'give every word an address',deck:'build a tiny memory from visible bits before using the larger memory interface.',minutes:30,phase:'03 / datapath → state',goals:['decode a write address','store two independent words','read without accidentally writing'],labs:['ram'],sources:[seq],questions:[
 q('we=0 and the clock rises. what should this memory do?',['clear the selected word','leave both words unchanged','copy the read output to both words'],1,'write enable selects the load path. without it, each storage bit recaptures its old value.','the address selects a word; it does not itself request a write.'),
 q('why does our final memory interface provide two asynchronous reads?',['one for instruction at PC, one for data at the instruction’s address','one read for positive numbers, one for negative numbers','to replace the accumulator'],0,'this removes a separate fetch state and instruction register, at the cost of a more capable memory interface and a longer combinational path.','the instruction tells us where its operand lives.') ]},
 {slug:'counter',title:'where do we go next?',deck:'build the program counter: a register, an incrementer, and a choice.',minutes:25,phase:'03 / datapath → state',goals:['construct an incrementer','select a branch target','explain wraparound and why there is no instruction interpreter'],labs:['counter'],sources:[],questions:[
 q('a six-bit PC contains 63 and increments. the new PC is…',['64','0','unchanged'],1,'only six result bits are stored; the carry into bit six is discarded.','there are 64 distinct six-bit addresses.'),
 q('which part remembers the program counter?',['the incrementer','its DFFs','the jump mux'],1,'the combinational incrementer and mux compute next values. the flip-flops hold the current value.','ask which component keeps its output between edges.') ]},
 {slug:'instructions',title:'four instructions, not magic',deck:'an instruction is data connected to a few control wires.',minutes:30,phase:'04 / state → computer',goals:['split an instruction into opcode and address','decode four mutually exclusive operations','derive the register and memory control signals'],labs:['decode'],sources:[],questions:[
 q('what does instruction 10 001101 mean?',['load memory[13]','subtract memory[13] from A','jump to 13'],1,'opcode 10 is SUB and address 001101 is 13.','our four opcodes are 00 load, 01 store, 10 subtract, 11 jump-if-zero.'),
 q('when is the accumulator allowed to change?',['on LDA or SUB','on every opcode','only on STA'],0,'LDA and SUB both have opcode bit 6 equal to 0. STA and JZ preserve A.','look at the low bit of the two-bit opcode.') ]},
 {slug:'computer',title:'put the whole thing together',deck:'repair and run the full gate-level cpu in the existing editor.',minutes:45,phase:'04 / state → computer',goals:['follow one instruction from PC to the next edge','find and repair a real missing wire','run five programs on the actual circuit'],labs:['computer'],sources:[source('the cpu source in this repository','/course-source/stupid.v')],questions:[
 q('how many CPU state bits does this design need, excluding memory?',['14: eight in A and six in PC','22: add an eight-bit instruction register','64'],0,'the instruction is supplied directly by asynchronous memory. there is no stored instruction or separate zero flag in this cpu.','count the individual DFFs, not the wires.'),
 q('on a store edge, memory must sample…',['the old settled instruction address and old accumulator','the next instruction after PC changes','whichever wire updates last'],0,'all sequential devices capture pre-edge inputs before any commit. otherwise execution becomes dependent on simulation evaluation order.','sampling and committing must be separate phases.') ]},
 {slug:'programming',title:'make it do something',deck:'labels, loops, and useful arithmetic on an intentionally tiny instruction set.',minutes:40,phase:'04 / state → computer',goals:['write a loop using only LDA / STA / SUB / JZ','separate an address from a constant','test a program on values you did not hardcode'],labs:['programming'],sources:[],questions:[
 q('with no JMP instruction, how can we jump unconditionally?',['load a known zero, then JZ target','STA target','subtract the target address'],0,'JZ always takes its branch when A is zero. a dedicated zero byte is a convenient convention.','our branch instruction has only one condition.'),
 q('a program passes for x=3 but fails for x=0. what does that show?',['the CPU needs an ADD opcode','one example was not enough to verify the algorithm','zero is not a legal byte'],1,'boundary cases exercise different branch paths and wraparound behavior. the grader tests six inputs, including zero and the high bit.','test the algorithm, not just one pleasing result.') ]},
 {slug:'verilog',title:'describe it, then build it',deck:'connect the readable program to the gates you have just assembled.',minutes:25,phase:'05 / computer → tools',goals:['distinguish RTL from executed software','generate a restricted gate netlist','separate synthesis from placement and routing'],labs:[],sources:[source('yosys · synthesis','https://yosyshq.readthedocs.io/projects/yosys/en/latest/cmd/synth.html'),source('yosys · technology mapping and dffunmap','https://yosyshq.readthedocs.io/projects/yosys/en/latest/cmd/index_passes_techmap.html')],questions:[
 q('inside a posedge block, a <= a - in_mem describes…',['a software subtraction instruction for another processor','combinational subtract logic feeding clocked storage','an analog voltage subtractor'],1,'synthesis infers next-state logic and flip-flops. there is no second CPU interpreting this statement.','you built the same feedback path in the accumulator lab.'),
 q('which job does not belong to RTL synthesis?',['lower a + b into logic','infer flip-flops from posedge blocks','choose 2D gate positions and route all wires'],2,'synthesis produces cells and nets. placement/routing converts that connectivity to geometry with real pin locations.','yosys gives the graph; the board router gives the drawing.') ]}
]
export const lessonBySlug=(slug:string)=>lessons.find(l=>l.slug===slug)
